# Generated by Django 5.2.8 on 2026-01-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
