# Generated by Django 5.2.8 on 2026-01-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_studentattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routine',
            options={'ordering': ['class_name', 'batch', 'day', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='routine',
            unique_together={('class_name', 'batch', 'day', 'start_time', 'end_time')},
        ),
        migrations.AddField(
            model_name='routine',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='routines', to='Home.routine'),
        ),
    ]
