# Generated by Django 5.2.8 on 2026-01-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_routine_options_alter_routine_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routine',
            options={'ordering': ['class_name', 'batch', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='routine',
            unique_together={('class_name', 'batch', 'start_time', 'end_time')},
        ),
        migrations.RemoveField(
            model_name='routine',
            name='day',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='days',
        ),
        migrations.AddField(
            model_name='routine',
            name='days',
            field=models.CharField(default='MON', help_text='Enter days separated by commas, e.g., MON,TUE,WED', max_length=100),
        ),
    ]
