# Generated by Django 5.2.8 on 2026-01-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_routine_options_alter_routine_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary_pending',
            field=models.BooleanField(default=True),
        ),
    ]
