# Generated by Django 5.2.8 on 2026-01-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_user_salary_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary_till_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
