# Generated by Django 5.2.8 on 2026-01-16 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_user_salary_till_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_pending', models.BooleanField(default=True)),
                ('fee_till_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fee_till_date'],
                'unique_together': {('student', 'fee_till_date')},
            },
        ),
    ]
