# Generated by Django 5.2.8 on 2026-01-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_studentfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fee_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fee_till_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
